# Generated by Django 3.1.1 on 2020-10-02 06:31

import django.contrib.postgres.fields
from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('u_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('email_verfy', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Premium_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('song_id', models.BigIntegerField(default=music.models.song.u_id, primary_key=True, serialize=False)),
                ('song_file', models.FileField(default='sss.mp3', upload_to='song')),
                ('artist', models.CharField(max_length=25)),
                ('album', models.CharField(max_length=25)),
                ('artist_img', models.ImageField(default='ssss.jpg', upload_to='img')),
                ('like', models.IntegerField(default=0)),
                ('listen_total', models.IntegerField(default=0)),
                ('listen_week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.BigIntegerField()),
                ('search', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None)),
                ('song_like', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('playlist_like', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('artist_like', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('albums_like', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
