# Generated by Django 3.1.1 on 2020-10-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='Premium_date',
            new_name='premium_date',
        ),
    ]
