# Generated by Django 3.1.1 on 2020-10-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201002_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_img',
            field=models.ImageField(default=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, upload_to='song'),
        ),
    ]
