# Generated by Django 3.1.1 on 2020-10-02 06:55

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20201002_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, upload_to=music.models.song.content_file_name_mp3),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='46122010225', primary_key=True, serialize=False),
        ),
    ]
