# Generated by Django 3.1.1 on 2020-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20201002_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='43122010226', primary_key=True, serialize=False),
        ),
    ]
