# Generated by Django 3.1.1 on 2020-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20201002_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='6122010233', primary_key=True, serialize=False),
        ),
    ]
