# Generated by Django 3.1.1 on 2020-10-02 07:03

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20201002_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_img',
            field=models.ImageField(default=None, upload_to=music.models.song.content_file_name_img),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='57122010233', primary_key=True, serialize=False),
        ),
    ]
