# Generated by Django 3.1.1 on 2020-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20201002_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_like',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='44162010247', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_like',
            name='u_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
