# Generated by Django 3.1.1 on 2020-10-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20201002_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='6172010245', primary_key=True, serialize=False),
        ),
    ]
