# Generated by Django 3.1.1 on 2020-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20201014_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_img',
            new_name='song_img',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='291520101433', primary_key=True, serialize=False),
        ),
    ]
