# Generated by Django 3.1.1 on 2020-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20201014_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='201520101440', primary_key=True, serialize=False),
        ),
    ]
