# Generated by Django 3.1.1 on 2020-11-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20201014_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(choices=[('sonu nigam', 'sonu nigam'), ('neha kakkar', 'neha kakkar'), ('sidhu moose wala', 'sidhu moose wala'), ('armaan malik', 'armaan malik'), ('arijit singh', 'arijit singh')], max_length=25),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.BigIntegerField(default='23172011628', primary_key=True, serialize=False),
        ),
    ]
